name: nostr_relay_management_api
description: Support for Nostr NIP-86 Relay Management API for Dart/Flutter applications.
version: 1.0.1
repository: https://github.com/anasfik/nostr_relay_management
documentation: https://github.com/anasfik/nostr_relay_management#
topics: 
  - nostr
  - relay
  - management
  - nip-86
  - client

environment:
  sdk: ^3.6.0


dependencies:
  dart_nostr: ^8.0.3
  crypto: ^3.0.6
  dio: ^5.9.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
